<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-G0T9AQE" failures="3" tests="6" name="Regression_Test" time="84.349" errors="0" timestamp="6 Apr 2021 22:43:57 GMT">
  <testcase classname="Jasper.Automation.Tests.Tests" name="Check_provisional_text_for_Privacy" time="1.42">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Jasper.Automation.Tests.Tests.Check_provisional_text_for_Privacy(Tests.java:109)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Check_provisional_text_for_Privacy -->
  <testcase classname="Jasper.Automation.Tests.Tests" name="Check_provisional_text_for_Terms_and_condition" time="1.44">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Jasper.Automation.Tests.Tests.Check_provisional_text_for_Terms_and_condition(Tests.java:97)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Check_provisional_text_for_Terms_and_condition -->
  <testcase classname="Jasper.Automation.Tests.Tests" name="Factorial_for_limit_value_171_is_Not_infinity" time="4.343">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Jasper.Automation.Tests.Tests.Factorial_for_limit_value_171_is_Not_infinity(Tests.java:84)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Factorial_for_limit_value_171_is_Not_infinity -->
  <testcase classname="Jasper.Automation.Tests.Tests" name="Get_factorial_for_limit_value_170" time="4.479"/>
  <testcase classname="Jasper.Automation.Tests.Tests" name="Get_factorial_for_limit_value_zero" time="4.364"/>
  <testcase classname="Jasper.Automation.Tests.Tests" name="Happy_path_Get_factorial_valid_num" time="4.277"/>
</testsuite> <!-- Regression_Test -->
